version: '3.8'

services:
  app:
    platform: linux/amd64
    build:
      context: .
    image: yourusername/device-management-system:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data:rw
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/devices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 