version: '3.8'

services:
  app:
    platform: linux/amd64
    build:
      context: .
    image: yourusername/device-management-system:latest
    ports:
      - "3000:3000"
    volumes:
      - db-data:/usr/src/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=UTC
      # Explicitly disable WAL to avoid cross-platform issues
      - SQLITE_DISABLE_WAL=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/devices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  db-data:
    driver: local 